"""Rebuild ytbrain/books/ligature_words.txt: the English words that contain a ligature (ff, fi, fl,
ffi, ffl) with how often they occur in your transcripts. `ytbrain.books.ligatures` uses it to repair
PDFs whose fonts lost their ligatures ("di@erent" -> "different").

    python scripts/ligature_words.py                 # reads data/transcripts/*.json
    python scripts/ligature_words.py --min-count 3   # a word must occur this often to count

Only word forms and counts are written, never any text. Damaged words ("di@erent") never match the
whole-word pattern below, so a book with lost ligatures adds only its intact words. Re-run after adding
many transcripts; the file is small and reviewed in the diff like any other data file."""
from __future__ import annotations

import argparse
import collections
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "ytbrain" / "books" / "ligature_words.txt"
WORD = re.compile(r"(?<![A-Za-z0-9@&%+=#<>^~|*$/_.-])[a-z]{3,24}(?![A-Za-z0-9@&%+=#<>^~|*$/_-])")
HAS_LIGATURE = re.compile(r"f[filf]")


def count(transcripts: Path) -> collections.Counter:
    seen: collections.Counter = collections.Counter()
    for f in sorted(transcripts.glob("*.json")):
        try:
            units = json.loads(f.read_text())["utterances"]
        except (OSError, ValueError, KeyError):
            continue
        for u in units:
            for w in WORD.findall(u.get("text", "")):
                if HAS_LIGATURE.search(w):
                    seen[w] += 1
    return seen


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--transcripts", type=Path, default=ROOT / "data" / "transcripts")
    ap.add_argument("--min-count", type=int, default=3)
    ap.add_argument("--out", type=Path, default=OUT)
    a = ap.parse_args(argv)
    seen = count(a.transcripts)
    words = sorted((w, n) for w, n in seen.items() if n >= a.min_count)
    if len(words) < 500:
        print(f"only {len(words)} words: is {a.transcripts} the transcripts folder?", file=sys.stderr)
        return 1
    header = ("# English words containing ff, fi, fl, ffi or ffl, with their count in a transcript corpus.\n"
              "# Generated by scripts/ligature_words.py; used by ytbrain/books/ligatures.py.\n")
    a.out.write_text(header + "".join(f"{w} {n}\n" for w, n in words))
    print(f"wrote {len(words)} words to {a.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
